[build-system]
requires = ["poetry-core>=2.1.0"]
build-backend = "poetry.core.masonry.api"

[project]
name = "rct-power"
version = "0.14.1"
license = "MIT"
description = ""
authors = [{ name = "Felix Stürmer", email = "stuermer@weltenwort.de" }]
requires-python = ">=3.13"
dynamic = ["classifiers", "dependencies"]

[tool.poetry]
packages = [
    { include = "rct_power", from = "custom_components" },
]

[tool.poetry.dependencies]
homeassistant = "^2025.2.5"
python = ">=3.13,<3.14"
rctclient = "^0.0.3"
getmac = "^0.9.5"

[tool.poetry.group.dev.dependencies]
pre-commit = "^4.1.0"
pytest = "^8.3.4"
pytest-homeassistant-custom-component = "^0.13.215"
mypy-dev = "^1.16.0a4"

[tool.pytest.ini_options]
asyncio_mode = "auto"

[tool.ruff.lint]
extend-select = [
    "I", # isort
]

[tool.mypy]
strict = true

[[tool.mypy.overrides]]
module = ["getmac.*"]
follow_untyped_imports = true
