[tool.poetry]
name = "rct-power"
version = "0.13.1"
description = ""
authors = ["Felix Stürmer <stuermer@weltenwort.de>"]
license = "MIT"

[tool.poetry.dependencies]
async_timeout = "^4.0.0"
homeassistant = "^2024.12.0"
python = ">=3.12,<3.14"
rctclient = "^0.0.3"

[tool.poetry.group.dev.dependencies]
homeassistant-stubs = "^2024.12.0"
pre-commit = "^4.0.1"
pytest = "^8.3.3"
pytest-homeassistant-custom-component = "^0.13.190"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pyright]
typeCheckingMode = "strict"
reportMissingTypeStubs = "none"
reportImportCycles = "warning"
useLibraryCodeForTypes = true

[tool.pytest.ini_options]
asyncio_mode = "auto"

[tool.isort]
profile = "black"
